projeto1/app/urls.py
from django.urls import path
import app.views as app_views

app_name = "app"

urlpatterns = [
    path("", app_views.home, name="home"),
    # Actors
    path("actor/", app_views.actor_endpoint, name="actor"),
    path("actor/<int:actor_id>", app_views.actor_endpoint, name="actor"),
    path("actor/search/", app_views.search_actor, name="actor_search"),
    # Directors
    path("director/", app_views.director_endpoint, name="director"),
    path("director/<int:director_id>", app_views.director_endpoint, name="director"),
    path("director/search/", app_views.search_director, name="director_search"),
    # Movies
    path("movie/", app_views.movie_endpoint, name="movie"),
    path("movie/<int:movie_id>", app_views.movie_endpoint, name="movie"),
    path("movie/search/", app_views.search_movie, name="movie_search"),
    # Languages
    path("language/", app_views.language_endpoint, name="language"),
    path("language/<int:language_id>", app_views.language_endpoint, name="language"),
    path("language/search/", app_views.search_language, name="language_search"),
    # Countries
    path("country/", app_views.country_endpoint, name="country"),
    path("country/<int:country_id>", app_views.country_endpoint, name="country"),
    path("country/search/", app_views.search_country, name="country_search"),
    # Genres
    path("genre/", app_views.genre_endpoint, name="genre"),
    path("genre/<int:genre_id>", app_views.genre_endpoint, name="genre"),
    path("genre/search/", app_views.search_genre, name="genre_search"),
    # Keywords
    path("keyword/", app_views.keyword_endpoint, name="keyword"),
    path("keyword/<int:keyword_id>", app_views.keyword_endpoint, name="keyword"),
    path("keyword/search/", app_views.search_keyword, name="keyword_search"),
    path("init_db/<int:confirmation>", app_views.start_script, name="exemplo")
]

projeto1/projeto1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("app.urls", namespace="app")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto1/app/templates/actor_pagination_old.html
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="hidden-xs col-sm-12 col-md-12 col-lg-12">
    <div class="visible-lg col-lg-1"></div>
    <div class="col-sm-4 col-md-5 col-lg-5 text-center" data-bind="foreach: previousActor">
      <div class="pull-left">
        <div class="h5"> Anterior</div>
        <img class="img-responsive" style="border-radius: 0.8em; margin:0.6em;"
             data-bind="attr: {src: photo, title:'Actor photo'}">
        <a data-bind="attr:{href: '?id='+ actorID}, text: actorName"></a>
      </div>
    </div>
    <div class="hidden-lg col-sm-4 col-md-2">
    </div>
    <div class="col-sm-4 col-md-5 col-lg-5 text-center" data-bind="foreach: nextActor">
      <div class="pull-right">
        <div class="h5"> Próximo</div>
        <img class="img-responsive" style="border-radius: 0.8em; margin:0.4em;"
             data-bind="attr: {src: photo, title:'Actor photo'}">
        <a data-bind="attr:{href: '?id='+ actorID}, text: actorName"></a>
      </div>
    </div>
    <div class="visible-lg col-lg-1"></div>
  </div>
  <div class="visible-xs col-xs-12">
    <div class="col-xs-5 text-center" data-bind="foreach: previousActor">
      <div class="pull-left">
        <div class="h5">Anterior</div>
        <img class="img-responsive" style="border-radius: 0.8em; margin:0.6em;"
             data-bind="attr: {src: photo, title:'Actor photo'}">
        <a data-bind="attr:{href: '?id='+ actorID}, text: actorName"></a>
      </div>
    </div>
    <div class="col-xs-2"></div>
    <div class="col-xs-5 text-center" data-bind="foreach: nextActor">
      <div class="h5">Próximo</div>
      <div class="pull-right">
        <img class="img-responsive" style="border-radius: 0.8em; margin:0.6em;"
             data-bind="attr: {src: photo, title:'Actor photo'}">
        <a data-bind="attr:{href: '?id='+ actorID}, text: actorName"></a>
      </div>
    </div>
  </div>
</div>
</div>

projeto1/app/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block page_title %}{% endblock %}</title>
  {% block common_css %}
    <link rel="stylesheet"
          href="{% static "bootstrap-4.3.1-dist/css/bootstrap.min.css" %}">
    <link rel="stylesheet"
          href="{% static "fontawesome-free-5.5.0-web/css/all.min.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static "custom.css" %}">
  {% endblock %}
  {% block page_css %}

  {% endblock %}

  {% block head_js %}
    <script src="{% static "jquery/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "popper.js/1.14.7/umd/popper.min.js" %}"></script>
    <script src="{% static "bootstrap-4.3.1-dist/js/bootstrap.min.js" %}">
    </script>
  {% endblock %}
</head>
<body>
  {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-fixed-top">
      <a class="navbar-brand" href="{% url 'app:home' %}">
        <i class="fa fa-film" aria-hidden="true"></i>&nbsp;IMDb5000+
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbar" style="height: 1px;">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item  {% if request.resolver_match.url_name == 'home' %} active {% endif %}">
            <a class="nav-link" href="{% url 'app:home' %}">Home
              {% if request.resolver_match.url_name == 'home' %}
                <span class="sr-only">(current)</span>
              {% endif %}
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropdownSearch" data-toggle="dropdown"
               role="button" aria-haspopup="true"
               aria-expanded="false">Pesquisa <span class="caret"></span></a>
            <div class="dropdown-menu" aria-labelled="dropdownSearch">
              <div class="dropdown-header">Pessoas</div>
              <a class="dropdown-item" data-toggle="modal" data-target="#modalAtores">Atores</a>
              <a class="dropdown-item" data-toggle="modal"
                 data-target="#modalDiretores">Diretores</a>
              <div class="dropdown-divider" role="separator"></div>
              <div class="dropdown-header">Filmes</div>
              <a class="dropdown-item" data-toggle="modal" data-target="#modalFilmes">Filmes</a>
              <a class="dropdown-item" data-toggle="modal" data-target="#modalPaises">Países</a>
              <a class="dropdown-item" data-toggle="modal" data-target="#modalGeneros">Generos</a>
              <a class="dropdown-item" data-toggle="modal" data-target="#modalLinguas">Linguas</a>
              <a class="dropdown-item" data-toggle="modal" data-target="#modalKeyword">Palavras-Chave</a>
            </div>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item"><a class="nav-link" href="#sobre">Sobre</a></li>
        </ul>
      </div>
    </nav>
  {% endblock %}
  {% block content %}
  {% endblock %}
  
  
  <!-- pesquisa de atores -->
  {% include 'actor_search.html' %}
  <!-- Pesquisa de Diretores -->
  {% include 'director_search.html' %}

  <!-- Pesquisa de Filmes -->
  {% include 'movie_search.html' %}
  <!-- Pesquisa de Países -->
  {% include 'country_search.html' %}
  <!-- Pesquisa de Generos -->
  {% include 'genre_search.html' %}


  <!-- Pesquisa de Linguas -->
  {% include "language_search.html" %}
  <!-- Pesquisa de Palavras chave-->
  {% include "keyword_search.html" %}
  {% block body_js %}
  {% endblock %}
</body>
</html>

projeto1/app/templates/country.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load app_extras %}
{% block content %}
  <div class="container" style="padding-top: 4em">
    <div class="row">
      <div class="col-12 ">
        <div class="d-flex flex-nowrap justify-content-around h1 text-center">

          <div class="d-none d-sm-block">
            {% if previous %}
              <div class="h4">Anterior</div>
              <a href="{% url 'app:country' previous.id %}">{{ previous.name }}</a>
            {% endif %}
          </div>

          <div>
            <div>{{ country.name }}</div>
            <small>ID:&nbsp;<strong>{{ country.id }}</strong></small>
            <small>Filmes:&nbsp;<strong> {{ movies.count }}</strong></small>
          </div>

          <div class="d-none d-sm-block">
            {% if next %}
              <div class="h4">Próximo</div>
              <a href="{% url 'app:country' next.id %}">{{ next.name }}</a>
            {% endif %}
          </div>

        </div>
      </div>
      <div class="col-12">
        <div class="h2 text-center">&nbsp;Filmes&nbsp;em&nbsp;<span>{{ country.name }}</span>
        </div>
        <div class="d-flex flex-wrap justify-content-around">
          {% for movie in movies %}
            <a class="mr-1 d-flex flex-nowrap flex-column justify-content-around align-items-center"
               href="{% url 'app:movie'  movie.id %}">
              <img src="{% no_movie_poster %}"
                   alt="Movie {{ movie.id }}"
                   class="center-block img-responsive">
              <span>{{ movie.movie_title }}</span>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

projeto1/app/templates/director.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load app_extras %}
{% block content %}
  <div class="container" style="padding-top: 4em">
    <div class="row">
      <!-- >= 768px-->
      <!-- director Photo -->
      <div class="col-md-4 col-lg-3">
        <img class="img-responsive rounded mb-3 mt-0 ml-3 mr-0 pr-0"
             alt="director Photo"
             src=" {% no_user_photo %}">
      </div>
      <!-- director Details Section-->
      <div class="col-md-8 col-lg-9 ">
        <div class="row">
          <div class="col-md-5 col-lg-6">
            <!-- director.name-->
            <div class="h3">
              {{ director.name }}
            </div>
          </div>
          <!-- director.facebook_likes-->
          <div class="col-md-4 col-lg-3">
            <div class="h3">
              {{ director.facebook_likes }}&nbsp;<i class="far fa-thumbs-up"></i>
            </div>
          </div>
          <!-- director.id -->
          <div class="col-md-3">
            <div class="h3">
              <small>ID:&nbsp;{{ director.id }}</small>
            </div>
          </div>
        </div>
        <div class="row">

        </div>
        <!-- director.unique-->
        <div class="col-md-12">
          <div>
            <div class="h4" style="display: inline-block;">Países:&nbsp;
              {% for country in unique_stats.countries %}
                <a class="d-inline-block"
                   href="{% url 'app:country' country.id %}"> {{ country.name }}</a>
              {% endfor %}
            </div>
          </div>
          <div>
            <div class="h4" style="display: inline-block;">Línguas:&nbsp;</div>
            {% for language in unique_stats.languages %}
              <a href="{% url 'app:language' language.id %}"> {{ language.name }}</a>
            {% endfor %}
          </div>
          <div>
            <div class="h4" style="display: inline-block;">Diretores:&nbsp;</div>
            {% for director in unique_stats.directors %}
              <a href="{% url 'app:director' director.id %}"> {{ director.name }}</a>
            {% endfor %}
          </div>
          <div>
            <div class="h4" style="display: inline-block;">Géneros:&nbsp;</div>
            {% for genre in unique_stats.genres %}
              <a href="{% url 'app:genre' genre.id %}"> {{ genre.name }}</a>
            {% endfor %}
          </div>

        </div>
      </div>

    </div>
    <div class="row">
      <div class="center-block table-responsive"
           style="padding: 0px; border-radius: 0.4em;">
        <table class="table table-striped text-center">
          <thead>
          <tr>
            <th class="text-center">Title</th>
            <th class="text-center">Year</th>
            <th class="text-center">IMDB</th>
            <th class="text-center">Score</th>
          </tr>
          </thead>
          <tbody>
          {% for movie in movies %}
            {% movies_to_table_row movie %}
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    {% director_pagination director %}
  </div>
{% endblock %}

projeto1/app/templates/director_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load app_extras %}
{% block content %}
  <div class="container" style="padding-top: 4em">
    <div class="row">
      <!-- >= 768px-->
      <!-- Director Photo -->
      <div class="col-md-4 col-lg-3 center-block">
        <img class="img-responsive"
             style="border-radius: 6px; margin:0.6em; float:right; align-content: right; align-items: right;"
             alt="Diretor Photo"
             src=" {% no_user_photo %}">
      </div>
      <!-- Director Details Section-->
      <div class="col-md-8 col-lg-9 " style="padding-left: 0px;">
        <div class="col-md-5 col-lg-6" style="padding-left: 0px;  padding-right: 0px;">
          <!-- Diretor.name-->
          <div class="h3"
               style="font-size: 1.75em;  padding-right: 0;">
            {{ director.name }}
          </div>
        </div>
        <!-- Director.facebook_likes-->
        <div class="col-md-4 col-lg-3 pull-left"
             style="padding-left: 0px; padding-right: 0px;">
          <div class="h3" style="font-size: 1.75em;  margin-bottom: 0px;">
            {{ director.facebook_likes }}&nbsp;<i class='fa fa-thumbs-o-up' aria-hidden='true'></i>
          </div>
        </div>
        <!-- Director.id -->
        <div class="col-md-3">
          <div class="h3">
            <small style="margin-bottom: 0; padding-right: 0;">
              ID:&nbsp;{{ director.id }}
            </small>
          </div>
        </div>
        <!-- Director.unique-->
        <div class="col-md-12">
          UNIQUE STATS
        </div>
      </div>

    </div>
    <div class="row">
      <div class="center-block table-responsive"
           style="padding: 0px; border-radius: 0.4em;">
        <table class="table table-striped text-center">
          <thead>
          <tr>
            <th class="text-center">Title</th>
            <th class="text-center">Year</th>
            <th class="text-center">OrderIn</th>
            <th class="text-center">IMDB</th>
            <th class="text-center">Score</th>
          </tr>
          </thead>
          <tbody>
          {% for movie in movies %}
            {% actor_movies_to_table_row movie %}
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      {% director_pagination director %}
    </div>
  </div>
{% endblock %}

projeto1/app/templates/director_search.html
{% load staticfiles %}
<script>
    var BASE_DIRECTOR_SEARCH = "{% url 'app:director_search' %}";
    var BASE_DIRECTOR = {% url 'app:director' %};
    $(document).ready(() => {
        function searchName(event) {
            let target = event.target;
            if (target.value.length < 3) {
                return;
            }
            // clear the results list
            $("#modalDiretoresResults").empty();
            let order_By = $("#ordenacaoDic").val();
            $.getJSON(BASE_DIRECTOR_SEARCH + `?name=${target.value}&order=${order_By}`, (data) => {
                var items = [];
                $.each(data, (k, v) => {
                    items.push(`<div class="col-md-6">
            <div><i class="fa fa-user"></i> <a
        href="${BASE_DIRECTOR + v.id}">${v.name} - ${v.facebook_likes}</a>
            </div>
          </div>`);
                });
                $("#modalDiretoresResults").append(items);
            });
        }

        $("#directorInput").on({
            'keyup': searchName
        });
        $("#ordenacaoDic").on({
            'change': searchName
        });
    });

</script>
<div id="modalDiretores" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Pesquisa de Diretores</h4>
      </div>
      <div class="modal-body">
        <p>A Base de Dados contem <span> {{ count }}</span> diretores.</p>
        <div class="col-lg-8 col-lg-offset-2 input-group">
          <span class="input-group-addon">Diretor:</span>
          <input id="directorInput" type="text" class="form-control"
                 placeholder="Nome do Diretor (3 ou mais letras)" />
        </div>
        <div class="col-lg-4 col-lg-offset-4" style="padding:10px 0px 10px 0px">
          <select id="ordenacaoDic" class="form-control">
            <option value="ALF" selected="true">Alfabéticamente</option>
            <option value="LIK">Gostos</option>
          </select>
        </div>
        <br />
        <div id="modalDiretoresResults" class="row">

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

projeto1/app/templates/genre.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load app_extras %}
{% block content %}
  <div class="container" style="padding-top: 4em">
    <div class="row">
      <div class="col-12 ">
        <div class="d-flex flex-nowrap justify-content-around h1 text-center">

          <div class="d-none d-sm-block">
            {% if previous %}
              <div class="h4">Anterior</div>
              <a href="{% url 'app:genre' previous.id %}">{{ previous.name }}</a>
            {% endif %}
          </div>

          <div>
            <div>{{ genre.name }}</div>
            <small>ID:&nbsp;<strong>{{ genre.id }}</strong></small>
            <small>Filmes:&nbsp;<strong> {{ movies.count }}</strong></small>
          </div>

          <div class="d-none d-sm-block">
            {% if next %}
              <div class="h4">Próximo</div>
              <a href="{% url 'app:genre' next.id %}">{{ next.name }}</a>
            {% endif %}
          </div>

        </div>
      </div>
      <div class="col-12">
        <div class="h2 text-center">&nbsp;Filmes&nbsp;de&nbsp;<span>{{ genre.name }}</span>
        </div>
        <div class="d-flex flex-wrap justify-content-around">
          {% for movie in movies %}
            <a class="mr-1 d-flex flex-nowrap flex-column justify-content-around align-items-center"
               href="{% url 'app:movie'  movie.id %}">
              <img src="{% no_movie_poster %}"
                   alt="Movie {{ movie.id }}"
                   class="center-block img-responsive">
              <span>{{ movie.movie_title }}</span>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

projeto1/app/templates/genre_search.html
{% load staticfiles %}
<script>
    var BASE_GENRE_SEARCH = "{% url 'app:genre_search' %}";
    var BASE_GENRE = {% url 'app:genre' %};
    $(document).ready(() => {
        function searchName(event) {
            let target = event.target;
            if (target.value.length < 1) {
                return;
            }
            // clear the results list
            $("#modalGenerosResults").empty();
            let order_By = $("#ordenacaoGenre").val();
            $.getJSON(BASE_GENRE_SEARCH + `?name=${target.value}&order=${order_By}`, (data) => {
                var items = [];
                $.each(data, (k, v) => {
                    items.push(`<div class="col-md-6">
            <div><i class="fa fa-rocket"></i> <a
        href="${BASE_GENRE + v.id}">${v.name}</a>
            </div>
          </div>`);
                });
                $("#modalGenerosResults").append(items);
            });
        }

        $("#genreInput").on({
            'keyup': searchName
        });
        $("#ordenacaoGenre").on({
            'change': $("#genreInput").trigger("keyup")
        });
    });

</script>
<div id="modalGeneros" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Pesquisa de Géneros</h4>
      </div>
      <div class="modal-body">
        <p>A Base de Dados contem <span> {{ count }}</span> Géneros.</p>
        <div class="col-lg-8 col-lg-offset-2 input-group">
          <span class="input-group-addon">Género:</span>
          <input id="genreInput" type="text" class="form-control"
                 placeholder="Nome do Género (1 ou mais letras)" />
        </div>
        <div class="col-lg-4 col-lg-offset-4" style="padding:10px 0px 10px 0px">
          <select id="ordenacaoGenre" class="form-control">
            <option value="ALF" selected="true">Alfabéticamente</option>
            <option value="MOV">Número de filmes</option>
          </select>
        </div>
        <br />
        <div id="modalGenerosResults" class="row">

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

projeto1/app/templates/language.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load app_extras %}
{% block content %}
  <div class="container" style="padding-top: 4em">
    <div class="row">
      <div class="col-12 ">
        <div class="d-flex flex-nowrap justify-content-around h1 text-center">

          <div class="d-none d-sm-block">
            {% if previous %}
              <div class="h4">Anterior</div>
              <a href="{% url 'app:language' previous.id %}">{{ previous.name }}</a>
            {% endif %}
          </div>

          <div>
            <div>{{ language.name }}</div>
            <small>ID:&nbsp;<strong>{{ language.id }}</strong></small>
            <small>Filmes:&nbsp;<strong> {{ movies.count }}</strong></small>
          </div>

          <div class="d-none d-sm-block">
            {% if next %}
              <div class="h4">Próxima</div>
              <a href="{% url 'app:language' next.id %}">{{ next.name }}</a>
            {% endif %}
          </div>

        </div>
      </div>
      <div class="col-12">
        <div class="h2 text-center">&nbsp;Filmes&nbsp;em&nbsp;<span>{{ language.name }}</span>
        </div>
        <div class="d-flex flex-wrap justify-content-around">
          {% for movie in movies %}
            <a class="mr-1 d-flex flex-nowrap flex-column justify-content-around align-items-center"
               href="{% url 'app:movie'  movie.id %}">
              <img src="{% no_movie_poster %}"
                   alt="Movie {{ movie.id }}"
                   class="center-block img-responsive">
              <span>{{ movie.movie_title }}</span>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

projeto1/app/templates/language_search.html
{% load staticfiles %}
<script>
    var BASE_LANGUAGE_SEARCH = "{% url 'app:language_search' %}";
    var BASE_LANGUAGE = {% url 'app:language' %};
    $(document).ready(() => {
        function searchName(event) {
            let target = event.target;
            if (target.value.length < 1) {
                return;
            }
            // clear the results list
            $("#modalLinguasResults").empty();
            $.getJSON(BASE_LANGUAGE_SEARCH + `?name=${target.value}`, (data) => {
                var items = [];
                $.each(data, (k, v) => {
                    items.push(`<div class="col-md-6">
            <div><i class="fa fa-language"></i> <a
        href="${BASE_LANGUAGE + v.id}">${v.name}</a>
            </div>
          </div>`);
                });
                $("#modalLinguasResults").append(items);
            });
        }

        $("#languageInput").on({
            'keyup': searchName
        });

    });

</script>
<div id="modalLinguas" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Pesquisa de Línguas</h4>
      </div>
      <div class="modal-body">
        <p>A Base de Dados contem <span> {{ count }}</span> Línguas.</p>
        <div class="col-lg-8 col-lg-offset-2 input-group">
          <span class="input-group-addon">Língua:</span>
          <input id="languageInput" type="text" class="form-control"
                 placeholder="Nome da Língua (1 ou mais letras)" />
        </div>
        <br />
        <div id="modalLinguasResults" class="row">

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

projeto1/app/templates/movie_search.html
{% load staticfiles %}
<script>
    var BASE_MOVIE_SEARCH = "{% url 'app:movie_search' %}";
    var BASE_MOVIE = {% url 'app:movie' %};
    $(document).ready(() => {
        function searchName(event) {
            let target = event.target;
            if (target.value.length < 3) {
                return;
            }
            // clear the results list
            $("#modalFilmesResults").empty();
            let order_By = $("#ordenacaoFil").val();
            $.getJSON(BASE_MOVIE_SEARCH + `?name=${target.value}&order=${order_By}`, (data) => {
                var items = [];
                $.each(data, (k, v) => {
                    items.push(`<div class="col-md-6">
            <div><i class="fa fa-film"></i> <a
        href="${BASE_MOVIE + v.id}"> ${v.title_year} - ${v.movie_title}</a>
            </div>
          </div>`);
                });
                $("#modalFilmesResults").append(items);
            });
        }

        $("#movieInput").on({
            'keyup': searchName
        });
        $("#ordenacaoFil").on({
            'change': searchName
        });
    });

</script>
<div id="modalFilmes" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Pesquisa de Filmes</h4>
      </div>
      <div class="modal-body">
        <p>A Base de Dados contem <span> {{ count }}</span> filmes.</p>
        <div class="col-lg-8 col-lg-offset-2 input-group">
          <span class="input-group-addon">Filme:</span>
          <input id="movieInput" type="text" class="form-control"
                 placeholder="Nome do Filme (3 ou mais letras)" />
        </div>
        <div class="col-lg-4 col-lg-offset-4" style="padding:10px 0px 10px 0px">
          <select id="ordenacaoFil" class="form-control">
            <option value="ALF" selected="true">Alfabéticamente</option>
            <option value="BUD">Budget</option>
            <option value="GRO">Vendas</option>
            <option value="YEAR">Ano</option>
          </select>
        </div>
        <br />
        <div id="modalFilmesResults" class="row">

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

projeto1/app/templates/random_actor_movies.html
  <div id="modalFilmesHighlight" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Filmes: </h4>
        </div>
        <div class="modal-body" data-bind="foreach: ator_aleatorio">
          <div class="row" data-bind="foreach: actor_movies">
            <div class="col-md-10 col-md-offset-1">
              <i class="fa fa-film"></i> <a
                data-bind="text: title_year + '&nbsp;&nbsp;&nbsp;&nbsp;' + imdb_score + '/10&nbsp;&nbsp;&nbsp;&nbsp;' + movie_title, attr: { href: './filme.html?id=' + movieID }"></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>